Lottery contract coverage
runtimeverification/elrond-semantics pull request #26
Opened 2020-12-03 16:05 UTC by hjorthjort

Adding support for the lottery-egld contract.

2020-12-04 13:51 UTC, andrei-marinica requested changes

2020-12-08 21:38 UTC, hjorthjort commented on elrond.md
> +    rule <instrs> hostCall("env", "int64storageStore", [ i32 i32 i64 .ValTypes ] -> [ i32 .ValTypes ] )
Which are the newer contracts? It seems it's present in the `lottery-egld` contract.

2020-12-08 21:41 UTC, hjorthjort commented on elrond.md
> +            <storage> STOR => STOR[String2Bytes("ELRONDrewards") <- #incBytes({STOR[String2Bytes("ELRONDrewards")]}:>Bytes, VAL)] </storage>
```suggestion
            <storage> STOR => STOR[String2Bytes("ELRONDrewards") <- #incBytes({STOR[String2Bytes("ELRONDrewards")]}:>Bytes, VAL)] </storage>
            <balance> TO_BAL => TO_BAL +Int VAL </balance>
```

2020-12-09 16:35 UTC, hjorthjort commented on elrond.md
> +    rule <instrs> hostCall("env", "int64storageStore", [ i32 i32 i64 .ValTypes ] -> [ i32 .ValTypes ] )
It seems it's not used anymore, so I removed it for now. Will add the others later.

2020-12-11 23:17 UTC, andrei-marinica approved these changes

2020-12-15 11:03 UTC, merged